import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Button } from "@/components/ui/button"
import { Toaster } from "@/components/ui/sonner"
import { auth } from "@/lib/auth.server"
import { headers } from "next/headers"
import Link from "next/link"
import UserDropdown from "@/components/UserDropdown"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Creators Nest",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
  user: userRoute,
}: Readonly<{
  children: React.ReactNode
  user: React.ReactNode
}>) {
  const session = await auth.api.getSession({ headers: await headers() })
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {session ? userRoute : children}
        <Toaster />
      </body>
    </html>
  )
}
